# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-13 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image1',
            field=models.ImageField(default='default.jpeg', upload_to='profile_pics'),
        ),
    ]
