# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-13 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image1',
            field=models.ImageField(default='default.jpeg', upload_to='book_pics'),
        ),
    ]
